//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstOracle
{
    using System;
    
    public partial class SpGetCourseTestCursor
    {
        public decimal COURSEID { get; set; }
        public decimal AUTHORID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal FULLPRICE { get; set; }
        public Nullable<decimal> LEVELL { get; set; }
    }
}
