//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstVidzyOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime RELEASEDATE { get; set; }
        public Nullable<byte> GENREID { get; set; }
    
        public virtual GENRE GENRE { get; set; }
    }
}
